<?php
/**
 * Created by IntelliJ IDEA.
 * User: Tom
 * Date: 17/03/2018
 * Time: 11:26
 */

require 'Controller.php';

class index extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function View()
    {
        parent::View(); // TODO: Change the autogenerated stub
    }
}