<?php
/**
 * Created by IntelliJ IDEA.
 * User: Tom
 * Date: 17/03/2018
 * Time: 11:26
 */

require 'Controller.php';
require $_SERVER['DOCUMENT_ROOT'] . '/models/indexModel.php';

class index extends Controller
{
    public $filePath;

    public function __construct()
    {
        parent::__construct();

        $this->filePath = [
            'homepage'
        ];
    }

    public function View($uri = false)
    {
        parent::View(); // TODO: Change the autogenerated stub
    }
}