<?php
/**
 * Created by IntelliJ IDEA.
 * User: Tom
 * Date: 02/04/2018
 * Time: 21:28
 */

require $_SERVER['DOCUMENT_ROOT'] . '/controllers/Controller.php';
require $_SERVER['DOCUMENT_ROOT'] . '/models/Users/logoutModel.php';

class logout extends Controller
{
    public $filePath;

    public function __construct()
    {
        parent::__construct();

        $this->filePath = [
            'Users',
            'logout'
        ];
    }

    public function View($uri = false)
    {
        // Set cookie expiry to a past time, forcing expiry.
        setcookie('session', '', time() - 1, '/');
        if (isset($_COOKIE['session'])) {
            header('Location: /logout');
        }

        parent::View(); // TODO: Change the autogenerated stub
    }
}