<?php
/**
 * Created by IntelliJ IDEA.
 * User: Tom
 * Date: 03/04/2018
 * Time: 00:22
 */
require $_SERVER['DOCUMENT_ROOT'] . '/controllers/Controller.php';
require $_SERVER['DOCUMENT_ROOT'] . '/models/Events/createModel.php';

class create extends Controller
{
    public $filePath;

    public function __construct()
    {
        parent::__construct();

        $this->filePath = [
            'Events',
            'create'
        ];
    }

    public function Post()
    {
        $model = new createModel();
        $id = $model->insert('events', $_POST);

        if (empty($id)) {
            // Something went wrong there...
        } else {
            header('Location: /events/view/'.$id);
        }
    }

    public function View($uri = false, $query = false)
    {
        parent::View(); // TODO: Change the autogenerated stub
    }
}